### ISSUE TITLE
NOT A ISSUE - more of a comment/thanks

### ISSUE THREAD

**Issue by loneicewolf** [mikepound/enigma#1]
Hello; First of all I want to say that - Computerphile - is amazing, and **You** are **Extremely Good at Explaining things!** I always watch videos with you in them; And this enigma git, is just - amazing. 

Great work! Keep it up!  And,

Have a **Great Corona-Free Year!**

//W

**Comment by mikepound** [comment]
Heh, thanks! I appreciate the kind words :) Have fun cracking some codes!
